google:
  client_id: ''
  client_secret: ''
  refresh_token: ''
  spreadsheet_key: ''
flickr:
  key: ''
  secret: ''
twitter:
  consumer_key: ''
  consumer_secret: ''
  access_token: ''
  access_token_secret: ''

