source 'https://rubygems.org'

gem 'flickraw'
gem 'google_drive'
gem 'instagram'
gem 'twitter'

gem 'rspec'

group :development do
  gem 'guard-rspec', require: false
  gem 'quiet_assets'
  gem 'terminal-notifier-guard'
end